### PR TITLE
Fix name of public network

### LINKED ISSUE #74: Wrong name for public network
I got this error when I tried to deploy:
```
network "nw-public" is declared as external, but could not be found. You need to create a swarm-scoped network before the stack is deployed
make: *** [deploy] Error 1
```

The problem is that the Docker stack now uses `nw-public`, but the ansible playbook still creates a network with the old name, `traefik-public`.

This suggests that we need a CI test which actually deploys the stack and verifies that it comes up.

### PR DESCRIPTION
**Pull request by davisagli**
Here are a couple places where the network names were wrong since https://github.com/collective/cookiecutter-plone-starter/commit/aafae8ef98f4e20b1d56b4de111c91a4b2a96c31

Should fix #74 I think

### CODE REVIEW

**Comment by jensens** [comment]
in most docs and tutorials it is referred to traefik-public. It could be confusing to use a different name.
Also, if you need another network for non-traefik  purposes, it is probably a better idea to add a dedicated network for this.

**Comment by davisagli** [comment]
@jensens I don't personally care which one we use, but currently we use both in different places and the deployment is broken.

**Comment by stevepiercy** [comment]
So this thing is a public network, right? IMO, we should not use the name of the application providing the implementation `traefik-public`, but should instead use a more descriptive and fully spelled out name `network-public`. `nw-public` made me think NorthWest public. Silly Oregonians!

**Comment by jensens** [comment]
This is a network meant to be shared by one or more Docker stacks to communicate with Traefik and nothing else. So `traefik-public` is the perfect name.

**Comment by jensens** [comment]
Here is more background information https://dockerswarm.rocks/traefik/

**Comment by jensens** [comment]
> Also, I would go with nw-public (as this could also be used by Varnish)

Indeed, a central general varnish could be part of this. 

I would then go with `nw-webserver` - `*public` is probably - even in conjunction with `traefik` - misleading.

**Comment by davisagli** [comment]
+1 for `nw-webserver` or `nw-web`. It has confused me before that that network is called "public" even though it is separate from the Docker swarm routing mesh that handles ingress traffic.

**Comment by davisagli** [comment]
@jensens @ericof I updated this PR to use `nw-webserver` as the network name

**Review by stevepiercy — APPROVED** [review]

**Review by jensens — APPROVED** [review]

**Pull request merged**
