### PR TITLE
Re-run CI when the GitHub Actions config changes

### PR DESCRIPTION
**Pull request by JeffersonBledsoe**

### CODE REVIEW

**Review by davisagli — APPROVED** [review]

**Comment by JeffersonBledsoe** [comment]
@davisagli Just had a though. Would we want to re-run the release step if the only thing that has changes is the CI config?

**Comment by davisagli** [comment]
@JeffersonBledsoe I think so. Maybe the change to the CI config is being done in order to fix a problem with the release step.

**Comment by davisagli** [comment]
@JeffersonBledsoe I like @mauritsvanrees' similar PR in #21 which also makes it possible to trigger the action manually

**Comment by JeffersonBledsoe** [comment]
Superseded by #21

**Pull request closed without merging**
