### PR TITLE
.gitlab-ci.yml file was misplaced

### PR DESCRIPTION
**Pull request by erral**
I'm really sorry about this, it looks like I pushed the wrong files to GitHub. I have realized that the `.gitlab-ci.yml` file was added to the wrong folder

### CODE REVIEW

**Comment by stevepiercy** [comment]
@erral there's a weird warning on this PR, something I have never seen before:

`The head ref may contain hidden characters: "erral-gitlab-misplaced\u00E7"`

Screenshot 2024-04-09 at 2 32 26 PM

**Review by stevepiercy — APPROVED** [review]
Other than that weird warning in GitHub, this LGTM.

**Comment by erral** [comment]
Yes when creating the branch with these changes y accidentally hit ç which in my keyboard is next to the return key, and thus the branch name contains that name 😅

**Comment by davisagli** [comment]
@erral You get a guy to help with translations, and suddenly funny characters start showing up :-p

**Review by davisagli — APPROVED** [review]

**Pull request merged**
