### PR TITLE
Add varnish configurations

### PR DESCRIPTION
**Pull request by margaridasp**

### CODE REVIEW

**Comment by ericof** [comment]
@fredvd, @margaridasp: This is ready to be tested then merged :-)

**Comment by fredvd** [comment]
@ericof  Is it possible with cookiecutter to address this branch as the cookiecutter source to test the new template?   

gh:collective/cookiecutter-plone-starter#add-caching-with-varnish doesn't work :-/

**Comment by ericof** [comment]
@fredvd 
`pipx run cookiecutter gh://... --checkout <branch name>`

**Review by fredvd — APPROVED** [review]
I've tested this setup locally with running docker-compose.yml and it seems to work.   I can't comment on the effectiveness of the Varnish setup.  We'll need to add this to some official PLone sites and test it there as well.  maybe plone.de and ploneconf. 

One generic issue I found is that Safari on Mac OS X refuses to support http://myprojectname.localhost:80/ wildcard.  

I also had an issue where I forgot to create the backend plone site with the make command,  my first attempt showed a 404 and that 404 response got stuck in the local browser cache. So I was debuggin for a while switched to another browser and it 'suddenly' worked.

**Review by fredvd — CHANGES_REQUESTED** [review]
One issue I overlooked. The generated README  template mentions a monorepo with three main folders: frontend, backend and devops. But there is  4th folder now, 'varnish'. It only contains a config file though. Shouldn't we better move the varnish config to 'devops' and consider varnish a 'support' service that shouldn't be in the top level folder?

**Comment by ericof** [comment]
> One issue I overlooked. The generated README template mentions a monorepo with three main folders: frontend, backend and devops. But there is 4th folder now, 'varnish'. It only contains a config file though. Shouldn't we better move the varnish config to 'devops' and consider varnish a 'support' service that shouldn't be in the top level folder?

Let me try to move Varnish inside devops and see how it goes

**Comment by ericof** [comment]
@fredvd: Moved `/varnish` to `/devops/varnish`

**Pull request merged**
