### PR TITLE
fix #54 enforce usage of docker buildkit

### LINKED ISSUE #54: Backend and frontend `make build-image` fails with invalid Dockerfile syntax
Trying to build the backend or frontend Docker images fails because the “here”-style syntax used with the Dockerfile RUN command does not work correctly in the most recent available Docker version. For instance, these ["RUN <<EOT ..."](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/backend/Dockerfile#L14-L20) lines in the backend Dockerfile fail like this:

```json
make build-image
+ which python3
+ python3 -c 'import sys; print((int(sys.version_info[0]), int(sys.version_info[1])) >= tuple(map(int, '\''3.8'\''.split('\''.'\''))))'
+ docker build . -t kenmanheimer/myr-plone-backend:latest -f Dockerfile --build-arg PLONE_VERSION=6.0.0
Sending build context to Docker daemon  2.483MB
Error response from daemon: dockerfile parse error line 15: unknown instruction: ./BIN/PIP
make: *** [Makefile:166: build-image] Error 1
```

A similar failure happens with similar syntax in the frontend Dockerfile [here](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/frontend/Dockerfile.default#L5-L10), [here](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/frontend/Dockerfile.default#L17-L20), and [here](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/frontend/Dockerfile.default#L29-L35).

Maybe the `here` syntax works on the version of Docker on someone’s system, but it does not work on the most recent version of Docker available for my Ubuntu 20.04 or Ubuntu 22.04 systems, Docker version 20.10.22 build 3a2c30b.

A solution that should work on recent Docker versions is to instead use continuation lines separated by `&&` command list operators, as is done with the LABEL statement elsewhere in both Dockerfiles, and typically with the RUN command in many Docker files.

I will file a pull request next.

### PR DESCRIPTION
**Pull request by jensens**
usage without buildkit is considered legacy by docker, see https://docs.docker.com/build/buildkit/

fixes #54

### CODE REVIEW

**Comment by jensens** [comment]
@kenmanheimer I am curious if this works in your environment.

**Review by kenmanheimer — COMMENTED** [review]
I'm hitting two problems with this:

* "@docker" is invalid. If you're carrying over the "don't echo" "@" at the beginning of a Makefile command line, it probable needs to be at the start of the line.
* The same syntax` error is still happening. I do have buildkit / the docker "buildx"  command installed, but the environment variable doesn't seem to be having the intended effect.

**Comment by davisagli** [comment]
@kenmanheimer What OS are you using and how did you install docker?

Thanks for checking, and I don't mean to imply that you did something wrong. I'm just trying to figure out if there are additional variables we haven't considered.

**Comment by kenmanheimer** [comment]
I think I learned what needs to be done to make the heredoc syntax work on docker in which buildkit/buildx included. On any of the platforms I've tried (detailed below) I needed to do `docker build buildx install`. That makes buildx available when using `docker build` going forward, unless and until you use `docker build buildx uninstall`. It was not available by default until I did that.

If this is correct then I see two drawbacks in using the heredoc syntax. First, it requires an additional configuration step. In contrast, the continuation-line "&&" syntax works in all cases, whether or not you have activated buildx mode. (It the line continuation syntax also appears to be quite commonly used.) Second, it is kind of invasive, requiring people to activate this mode in order to do the packages build. (Perhaps it will eventually become the default, but at least on the docker installs on the three systems detailed below it so far is not.) I don't see advantages in using the heredoc syntax and do see (and have been tried up by) disadvantages.

The systems involved:

1. A headless Digital Ocean droplet running Ubuntu 22.04.
2. An Intel Xeon headless server running Ubuntu 20.04.
3. A Pixelbook Go with Crostini's default Debian Raspbian 11.

I had to use a few different docker install methods on the different platforms, for various reasons. (Debian Raspbian 11 in Crostini was particularly tricky, and required some heavy finessing to get rooted operation without sudo, something also necessary for the Plone 6 packages install. Worth it, though, to get Plone 6 with Volto serving in my Chromebook.) `buildx` mode was not installed/active by default on any I am using, but perhaps it is in some contexts?

All in all, it's already complex getting the packages install to work. I would opt for the syntax that does not add another environment configuration requirement.

**Comment by kenmanheimer** [comment]
(Having read the suggested [buildkit overview](see https://docs.docker.com/build/buildkit/), I see that instituting use of buildkit and buildx would be valuable. I am not sure that using syntax that depends on it is a good way to go about that, though. Migrating to a non-backwards compatible version is a tricky proposition, and probably requires primary focus.)

**Comment by kenmanheimer** [comment]
So I see two things needed for the proposed changes:
1. Move the "@" signs to the beginning of the text but after the tab on each line, eg: 
     ` <tab>@DOCKER_BUILDKIT=1 docker ...`
3. Include in the instructions that the user must do a `docker buildx install` , per [Set Buildx as the default builder](https://docs.docker.com/build/install-buildx/#set-buildx-as-the-default-builder)

**Comment by jensens** [comment]
> * "@docker" is invalid. If you're carrying over the "don't echo" "@" at the beginning of a Makefile command line, it probable needs to be at the start of the line.

m( fixed that

**Comment by jensens** [comment]
>  I needed to do docker buildx install. That makes buildx available when using docker build going forward, unless and until you use docker buildx uninstall. It was not available by default until I did the install.

Very strange, "my" docker has noch `buildx install`

```
$ docker buildx --help

Usage:  docker buildx [OPTIONS] COMMAND

Extended build capabilities with BuildKit

Options:
      --builder string   Override the configured builder instance

Management Commands:
  imagetools  Commands to work on images in registry

Commands:
  bake        Build from a file
  build       Start a build
  create      Create a new builder instance
  du          Disk usage
  inspect     Inspect current builder instance
  ls          List builder instances
  prune       Remove build cache
  rm          Remove a builder instance
  stop        Stop builder instance
  use         Set the current builder instance
  version     Show buildx version information
  

$ docker --version
Docker version 20.10.22, build 3a2c30b
```

**Review by ericof — APPROVED** [review]

**Pull request merged**
