### PR TITLE
Replace `local` with `dev` for macOS

### PR DESCRIPTION
**Pull request by stevepiercy**
Fixes https://github.com/collective/cookiecutter-plone-starter/issues/36

### CODE REVIEW

**Comment by ericof** [comment]
I would suggest you rename `.env_local` to `.env_dev` and update `{{ cookiecutter.project_slug }}/devops/README.md` accordingly

**Comment by stevepiercy** [comment]
> I would suggest you rename `.env_local` to `.env_dev` and update `{{ cookiecutter.project_slug }}/devops/README.md` accordingly

Done in [282dbdd](https://github.com/collective/cookiecutter-plone-starter/pull/37/commits/282dbddcd4945f4405201a83ab47ea366c70b248).

I pulled this out of draft for final review.

I will also need to update the docs in a separate PR, but I am waiting for the next release of the cookiecutter to verify it all works.

**Comment by stevepiercy** [comment]
Training docs update queued for review https://github.com/plone/training/pull/694

**Review by ericof — APPROVED** [review]
LGTM

**Pull request merged**
